# Generated by Django 4.2 on 2023-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="realized_at",
            field=models.DateTimeField(verbose_name="date of the assignment"),
        ),
    ]
